version: '3.1'

services:

  uda_db:
    container_name: ${CONTAINER_NAME}
    build: ""
    ports:
      - 1480:5433/tcp
    environment:
      ACCEPT_EULA: ${MSSQL_SA_LICENCE_AGREEMENT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MSSQL_AGENT_ENABLED: ${MSSQL_AGENT_ENABLED}