@startuml
entity employee{
  *id : int
  --
  first_name :    varchar(100)
  last_name :     varchar(100)
  full_name:      varchar(100)
  date_of_birth:  date
  active:         bit
  **department_id   int
}

entity department{
  *id : int
  --
  name :         varchar(100)
  location :     varchar(100)
  no_of_offices: int
}

entity example{
  *id : int
  --
  col1 :         varchar(100)
  col2 :         varchar(100)
}

department "1" *-- "many" employee : contains

@enduml