server:
  port: 9000
spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1475;databaseName=uda;sendTimeAsDateTime=false;queryTimeout=10
    username: SA
    password: Abc@1234